defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: chayote_development

test:
  <<: *defaults
  database: chayote_test

# set these environment variables on your prod server
production:
  host: ds119768.mlab.com
  port: 19768
  username: admin
  password: admin
  database: heroku_479c0k66